# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmail" do
  name "agentmail"
  desc "The official CLI for AgentMail."
  homepage "https://agentmail.to"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmail"
  manpage "man/man1/agentmail.1.gz"
  bash_completion "completions/agentmail.bash"
  zsh_completion "completions/agentmail.zsh"
  fish_completion "completions/agentmail.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_amd64.zip"
      sha256 "324b7955d4d04b943cb6f3c66738436919ba5eb6cab30a037af3ca59b229616a"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_arm64.zip"
      sha256 "a3476f147c988f3ce44bb6a904e761b51d3dbbc1ec9ae0f2d2bee372d63b17a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_amd64.tar.gz"
      sha256 "de1a54cc647f2f1f2f06a41c41782ac609c1872f79523ea6b930dce044eac47c"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_arm64.tar.gz"
      sha256 "9d481b7a6a083e735f639e44a107f2d85642bdd3d4f316a00c4bea783f578ef3"
    end
  end

  # No zap stanza required
end
