# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmail" do
  name "agentmail"
  desc "The official CLI for AgentMail."
  homepage "https://agentmail.to"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmail"
  manpage "man/man1/agentmail.1.gz"
  bash_completion "completions/agentmail.bash"
  zsh_completion "completions/agentmail.zsh"
  fish_completion "completions/agentmail.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_amd64.zip"
      sha256 "a720597d4a3abd94b4b313bbb33ea32f218cedb5142bb614541b1cca10ff4c01"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_arm64.zip"
      sha256 "89a45a75b2a028b97c1da4c0ed0676159420d759ee71e0ecbe4c3537804b0f63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_amd64.tar.gz"
      sha256 "f43448407f8b92d756c9882ff7a25cc6105ec774e09b6a2261c112c61e644d9a"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_arm64.tar.gz"
      sha256 "d2c683f9a0b95d37f994490ddddf068ea12056683c85f9f4bda48fcfa47a65b0"
    end
  end

  # No zap stanza required
end
