# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentmail" do
  name "agentmail"
  desc "The official CLI for AgentMail."
  homepage "https://agentmail.to"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentmail"
  manpage "man/man1/agentmail.1.gz"
  bash_completion "completions/agentmail.bash"
  zsh_completion "completions/agentmail.zsh"
  fish_completion "completions/agentmail.fish"

  on_macos do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_amd64.zip"
      sha256 "f7000802fa89c06ffddb05d80a2897c79bfeceb79466f136b466278a3ed2a132"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_macos_arm64.zip"
      sha256 "05e2d8486ef8ec4c2b281e40ab2415d4e1f07580a63c52683edf413b03061347"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_amd64.tar.gz"
      sha256 "fdf2020cd0db9e8d5e68c35826f2af2dd4ccd54f498df2996c232d4c189424fc"
    end
    on_arm do
      url "https://github.com/agentmail-to/agentmail-cli/releases/download/v#{version}/agentmail_#{version}_linux_arm64.tar.gz"
      sha256 "270d6696b834a877033d1a2c67bc5198f3676870229a84aecb85e3202ee575e2"
    end
  end

  # No zap stanza required
end
